name: Deploy Backend

on:
  push:
    branches:
      - jinhwan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install dependencies
        run: ./gradlew clean build

      - name: Deploy to AWS EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/libs/ainstyle-back-0.0.1-SNAPSHOT.jar"
          REMOTE_HOST: "43.202.54.163"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/ainstyle-back/"
      
      - name: Restart Backend Service
        run: |
          ssh -i ~/.ssh/your_key.pem ubuntu@43.202.54.163 'pm2 restart ainstyle-backend || pm2 start /home/ubuntu/ainstyle-back/ainstyle-back-0.0.1-SNAPSHOT.jar --name "ainstyle-backend"'
